"""
Market Research Report Generation System

This module provides comprehensive report generation capabilities for 3C analysis,
extending the existing reporting infrastructure with specialized market research formatting.
"""

import logging
from typing import Dict, List, Any, Optional, Set
from datetime import datetime
from dataclasses import asdict
import re
import json
import csv
import io
import base64
from pathlib import Path

# Import libraries for advanced export formats
try:
    import markdown
    MARKDOWN_AVAILABLE = True
except ImportError:
    MARKDOWN_AVAILABLE = False

try:
    from jinja2 import Template
    JINJA2_AVAILABLE = True
except ImportError:
    JINJA2_AVAILABLE = False

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

# WeasyPrint removed due to system dependencies
WEASYPRINT_AVAILABLE = False

from backend.classes.state import MarketResearchState, ConsumerInsight, MarketTrend, CompetitorProfile, MarketOpportunity

logger = logging.getLogger(__name__)


class MarketResearchReportGenerator:
    """
    Generates comprehensive 3C analysis reports with structured formatting,
    insight synthesis, and duplicate removal capabilities.
    """
    
    def __init__(self):
        self.export_formats = ['markdown', 'html', 'pdf', 'json', 'csv']
        self.section_templates = self._initialize_templates()
        self.html_template = self._initialize_html_template()
        self.report_metadata = {
            'version': '1.0',
            'generator': 'AI-powered 3C Analysis System',
            'created_at': datetime.now().isoformat()
        }
        
    def _initialize_templates(self) -> Dict[str, str]:
        """Initialize report section templates"""
        return {
            'header': """# 3C Analysis Report: {target_market} Market

**Analysis Type:** {analysis_type}  
**Market Segment:** {market_segment}  
**Generated:** {timestamp}  
**Report ID:** {report_id}

---
""",
            'executive_summary': """## Executive Summary

{summary_content}

### Key Findings
{key_findings}

---
""",
            'consumer_analysis': """## Consumer Analysis

{consumer_content}

---
""",
            'trend_analysis': """## Market Trends Analysis

{trend_content}

---
""",
            'competitor_analysis': """## Competitive Landscape

{competitor_content}

---
""",
            'opportunity_analysis': """## Market Opportunities

{opportunity_content}

---
""",
            'footer': """---

### Report Metadata
- **Data Sources:** {data_sources}
- **Analysis Confidence:** {confidence_score}
- **Report Version:** 1.0

*This report was generated by the AI-powered 3C Analysis System*
"""
        }
    
    def _initialize_html_template(self) -> str:
        """Initialize HTML template for report export"""
        return """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8f9fa;
        }
        .container {
            background-color: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }
        h2 {
            color: #34495e;
            border-left: 4px solid #3498db;
            padding-left: 15px;
            margin-top: 40px;
            margin-bottom: 20px;
        }
        h3 {
            color: #2c3e50;
            margin-top: 30px;
            margin-bottom: 15px;
        }
        .metadata {
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 30px;
            font-size: 0.9em;
        }
        .key-findings {
            background-color: #e8f6f3;
            border-left: 4px solid #1abc9c;
            padding: 20px;
            margin: 20px 0;
        }
        .insight-item {
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            padding: 15px;
            margin: 10px 0;
        }
        .source-attribution {
            font-style: italic;
            color: #6c757d;
            font-size: 0.85em;
            margin-top: 5px;
        }
        .competitor-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        .competitor-table th,
        .competitor-table td {
            border: 1px solid #dee2e6;
            padding: 12px;
            text-align: left;
        }
        .competitor-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .opportunity-card {
            background-color: #fff3cd;
            border: 1px solid #ffeaa7;
            border-radius: 5px;
            padding: 15px;
            margin: 10px 0;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            font-size: 0.9em;
            color: #6c757d;
        }
        @media print {
            body { background-color: white; }
            .container { box-shadow: none; }
        }
    </style>
</head>
<body>
    <div class="container">
        {{ content }}
    </div>
</body>
</html>
        """
    
    async def generate_3c_report(self, state: MarketResearchState) -> str:
        """
        Generate a comprehensive 3C analysis report from the market research state.
        
        Args:
            state: MarketResearchState containing all analysis results
            
        Returns:
            str: Formatted markdown report
        """
        try:
            logger.info(f"Generating 3C report for {state.get('target_market', 'Unknown Market')}")
            
            # Generate unique report ID
            report_id = self._generate_report_id(state)
            
            # Synthesize insights and remove duplicates
            synthesized_data = await self._synthesize_insights(state)
            
            # Build report sections
            sections = []
            
            # Header section
            sections.append(self._generate_header_section(state, report_id))
            
            # Executive summary
            sections.append(await self._generate_executive_summary(state, synthesized_data))
            
            # Consumer analysis section
            sections.append(await self._generate_consumer_section(state, synthesized_data))
            
            # Trend analysis section
            sections.append(await self._generate_trend_section(state, synthesized_data))
            
            # Competitor analysis section
            sections.append(await self._generate_competitor_section(state, synthesized_data))
            
            # Opportunity analysis section
            sections.append(await self._generate_opportunity_section(state, synthesized_data))
            
            # Footer section
            sections.append(self._generate_footer_section(state, synthesized_data))
            
            # Combine all sections
            full_report = "\n".join(sections)
            
            logger.info(f"Successfully generated 3C report ({len(full_report)} characters)")
            return full_report
            
        except Exception as e:
            logger.error(f"Error generating 3C report: {e}")
            return self._generate_error_report(state, str(e))
    
    def _generate_report_id(self, state: MarketResearchState) -> str:
        """Generate a unique report identifier"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        market = state.get('target_market', 'unknown').replace(' ', '_').lower()
        return f"3c_{market}_{timestamp}"
    
    async def _synthesize_insights(self, state: MarketResearchState) -> Dict[str, Any]:
        """
        Synthesize and deduplicate insights from all analysis agents.
        
        Returns:
            Dict containing synthesized and deduplicated data
        """
        try:
            synthesized = {
                'consumer_insights': self._deduplicate_consumer_insights(state),
                'market_trends': self._deduplicate_market_trends(state),
                'competitor_profiles': self._deduplicate_competitor_data(state),
                'opportunities': self._deduplicate_opportunities(state),
                'data_quality': self._assess_data_quality(state),
                'key_metrics': self._calculate_key_metrics(state)
            }
            
            return synthesized
            
        except Exception as e:
            logger.error(f"Error synthesizing insights: {e}")
            
            # Return synthesized data with error handling
            return {
                'consumer_insights': self._safe_deduplicate_consumer_insights(state),
                'market_trends': self._safe_deduplicate_market_trends(state),
                'competitor_profiles': self._handle_competitor_analysis_error(state, e),
                'opportunities': self._safe_deduplicate_opportunities(state),
                'data_quality': self._assess_data_quality(state),
                'key_metrics': self._calculate_key_metrics(state)
            }
    
    def _safe_deduplicate_consumer_insights(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Safely deduplicate consumer insights with error handling"""
        try:
            return self._deduplicate_consumer_insights(state)
        except Exception as e:
            logger.error(f"Error deduplicating consumer insights: {e}")
            return []
    
    def _safe_deduplicate_market_trends(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Safely deduplicate market trends with error handling"""
        try:
            return self._deduplicate_market_trends(state)
        except Exception as e:
            logger.error(f"Error deduplicating market trends: {e}")
            return []
    
    def _safe_deduplicate_opportunities(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Safely deduplicate opportunities with error handling"""
        try:
            return self._deduplicate_opportunities(state)
        except Exception as e:
            logger.error(f"Error deduplicating opportunities: {e}")
            return []
    
    def _deduplicate_consumer_insights(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Remove duplicate consumer insights based on content similarity"""
        consumer_insights = state.get('consumer_insights', {})
        
        if not consumer_insights or not consumer_insights.get('structured_insights'):
            return []
        
        insights = consumer_insights['structured_insights']
        deduplicated = []
        seen_content = set()
        
        for insight in insights:
            content = insight.get('extracted_insight', '').lower().strip()
            
            # Create a normalized version for comparison
            normalized = re.sub(r'[^\w\s]', '', content)
            normalized = ' '.join(normalized.split())
            
            # Check for similarity with existing insights
            is_duplicate = False
            for seen in seen_content:
                if self._calculate_similarity(normalized, seen) > 0.6:  # Lower threshold for better deduplication
                    is_duplicate = True
                    break
            
            if not is_duplicate and len(normalized) > 10:
                seen_content.add(normalized)
                deduplicated.append(insight)
        
        return deduplicated[:10]  # Limit to top 10 insights
    
    def _deduplicate_market_trends(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Remove duplicate market trends based on content similarity"""
        market_trends = state.get('market_trends', {})
        
        if not market_trends or not market_trends.get('structured_trends'):
            return []
        
        trends = market_trends['structured_trends']
        deduplicated = []
        seen_trends = set()
        
        for trend in trends:
            trend_text = trend.get('extracted_trends', '').lower().strip()
            
            # Normalize trend text
            normalized = re.sub(r'[^\w\s]', '', trend_text)
            normalized = ' '.join(normalized.split())
            
            # Check for duplicates
            is_duplicate = False
            for seen in seen_trends:
                if self._calculate_similarity(normalized, seen) > 0.7:
                    is_duplicate = True
                    break
            
            if not is_duplicate and len(normalized) > 10:
                seen_trends.add(normalized)
                deduplicated.append(trend)
        
        return deduplicated[:8]  # Limit to top 8 trends
    
    def _deduplicate_competitor_data(self, state: MarketResearchState) -> Dict[str, Any]:
        """Process and deduplicate competitor analysis data"""
        competitor_landscape = state.get('competitor_landscape', {})
        competitive_positioning = state.get('competitive_positioning', {})
        feature_comparisons = state.get('feature_comparisons', [])
        
        # Handle pending status (for backward compatibility with tests)
        if competitor_landscape.get('status') == 'pending':
            return {
                'status': 'pending',
                'competitors': [],
                'key_players': [],
                'market_share_data': {},
                'positioning_strategies': {},
                'feature_comparisons': [],
                'message': 'Competitive landscape analysis is pending completion of the competitor analysis agent (Task 4).'
            }
        
        if not competitor_landscape or competitor_landscape.get('status') in ['failed', 'no_data_available']:
            return {
                'status': 'failed',
                'competitors': [],
                'key_players': [],
                'market_share_data': {},
                'positioning_strategies': {},
                'feature_comparisons': [],
                'error_message': 'Competitor analysis data unavailable'
            }
        
        # Process competitor landscape data
        competitors = competitor_landscape.get('competitors', [])
        key_players = competitor_landscape.get('key_players', [])
        market_share_data = competitor_landscape.get('market_share_data', {})
        
        # Deduplicate competitors
        unique_competitors = []
        seen_competitors = set()
        
        for competitor in competitors:
            competitor_name = competitor.lower().strip() if isinstance(competitor, str) else str(competitor).lower().strip()
            normalized_name = re.sub(r'[^\w\s]', '', competitor_name)
            normalized_name = ' '.join(normalized_name.split())
            
            if normalized_name and len(normalized_name) > 2 and normalized_name not in seen_competitors:
                seen_competitors.add(normalized_name)
                unique_competitors.append(competitor)
        
        # Deduplicate key players
        unique_key_players = []
        seen_key_players = set()
        
        for player in key_players:
            player_name = player.lower().strip() if isinstance(player, str) else str(player).lower().strip()
            normalized_name = re.sub(r'[^\w\s]', '', player_name)
            normalized_name = ' '.join(normalized_name.split())
            
            if normalized_name and len(normalized_name) > 2 and normalized_name not in seen_key_players:
                seen_key_players.add(normalized_name)
                unique_key_players.append(player)
        
        # Process positioning strategies
        positioning_strategies = competitive_positioning.get('positioning_strategies', {})
        
        # Process feature comparisons
        deduplicated_features = []
        seen_feature_competitors = set()
        
        for comparison in feature_comparisons:
            competitor_name = comparison.get('competitor', '').lower().strip()
            if competitor_name and competitor_name not in seen_feature_competitors:
                seen_feature_competitors.add(competitor_name)
                deduplicated_features.append(comparison)
        
        return {
            'status': 'success',
            'competitors': unique_competitors[:10],  # Limit to top 10
            'key_players': unique_key_players[:5],   # Limit to top 5
            'market_share_data': market_share_data,
            'positioning_strategies': positioning_strategies,
            'feature_comparisons': deduplicated_features[:5],  # Limit to top 5
            'total_competitors_found': len(unique_competitors),
            'data_sources': competitor_landscape.get('data_sources', 0)
        }
    
    def _deduplicate_opportunities(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Remove duplicate opportunities and white spaces"""
        opportunities = state.get('opportunities', [])
        white_spaces = state.get('white_spaces', [])
        
        all_opportunities = opportunities + white_spaces
        deduplicated = []
        seen_titles = set()
        
        for opp in all_opportunities:
            title = opp.get('title', '').lower().strip()
            
            if title and title not in seen_titles:
                seen_titles.add(title)
                deduplicated.append(opp)
        
        return deduplicated[:6]  # Limit to top 6 opportunities
    
    def _calculate_similarity(self, text1: str, text2: str) -> float:
        """Calculate simple similarity score between two text strings"""
        if not text1 or not text2:
            return 0.0
        
        words1 = set(text1.split())
        words2 = set(text2.split())
        
        if not words1 or not words2:
            return 0.0
        
        intersection = words1.intersection(words2)
        union = words1.union(words2)
        
        return len(intersection) / len(union) if union else 0.0
    
    def _assess_data_quality(self, state: MarketResearchState) -> Dict[str, Any]:
        """Assess the quality and completeness of collected data"""
        quality_metrics = {
            'overall_score': 0.0,
            'consumer_data_quality': 'unknown',
            'trend_data_quality': 'unknown',
            'competitor_data_quality': 'unknown',
            'data_completeness': 0.0
        }
        
        # Assess consumer data quality
        consumer_insights = state.get('consumer_insights', {})
        if consumer_insights and consumer_insights.get('structured_insights'):
            insights_count = len(consumer_insights['structured_insights'])
            quality_metrics['consumer_data_quality'] = 'high' if insights_count >= 5 else 'medium' if insights_count >= 2 else 'low'
        
        # Assess trend data quality
        market_trends = state.get('market_trends', {})
        if market_trends and market_trends.get('structured_trends'):
            trends_count = len(market_trends['structured_trends'])
            quality_metrics['trend_data_quality'] = 'high' if trends_count >= 3 else 'medium' if trends_count >= 1 else 'low'
        
        # Assess competitor data quality
        competitor_landscape = state.get('competitor_landscape', {})
        if competitor_landscape and competitor_landscape.get('status') not in ['failed', 'no_data_available']:
            competitors_count = len(competitor_landscape.get('competitors', []))
            key_players_count = len(competitor_landscape.get('key_players', []))
            
            if competitors_count >= 5 and key_players_count >= 2:
                quality_metrics['competitor_data_quality'] = 'high'
            elif competitors_count >= 2 or key_players_count >= 1:
                quality_metrics['competitor_data_quality'] = 'medium'
            else:
                quality_metrics['competitor_data_quality'] = 'low'
        else:
            quality_metrics['competitor_data_quality'] = 'unavailable'
        
        # Calculate overall completeness
        completeness_factors = []
        if quality_metrics['consumer_data_quality'] in ['high', 'medium']:
            completeness_factors.append(1.0)
        if quality_metrics['trend_data_quality'] in ['high', 'medium']:
            completeness_factors.append(1.0)
        if quality_metrics['competitor_data_quality'] in ['high', 'medium']:
            completeness_factors.append(1.0)
        
        quality_metrics['data_completeness'] = sum(completeness_factors) / 3.0
        quality_metrics['overall_score'] = quality_metrics['data_completeness']
        
        return quality_metrics
    
    def _calculate_key_metrics(self, state: MarketResearchState) -> Dict[str, int]:
        """Calculate key metrics for the executive summary"""
        consumer_insights = state.get('consumer_insights', {})
        market_trends = state.get('market_trends', {})
        pain_points = state.get('pain_points', [])
        opportunities = state.get('opportunities', [])
        white_spaces = state.get('white_spaces', [])
        
        return {
            'consumer_insights_count': len(consumer_insights.get('structured_insights', [])),
            'pain_points_identified': len(pain_points),
            'market_trends_identified': len(market_trends.get('structured_trends', [])),
            'opportunities_identified': len(opportunities),
            'white_spaces_found': len(white_spaces),
            'total_recommendations': len(state.get('recommendations', []))
        }
    
    def _format_data_quality(self, quality: str) -> str:
        """Format data quality description to avoid 'unknown'"""
        if quality == 'unknown':
            return 'pending'
        elif quality == 'unavailable':
            return 'not available'
        else:
            return quality
    
    def _handle_competitor_analysis_error(self, state: MarketResearchState, error: Exception) -> Dict[str, Any]:
        """Handle competitor analysis errors gracefully"""
        logger.error(f"Competitor analysis error: {error}")
        
        return {
            'status': 'failed',
            'competitors': [],
            'key_players': [],
            'market_share_data': {},
            'positioning_strategies': {},
            'feature_comparisons': [],
            'error_message': f'Competitor analysis failed: {str(error)}',
            'fallback_data': self._get_fallback_competitor_data(state)
        }
    
    def _get_fallback_competitor_data(self, state: MarketResearchState) -> Dict[str, Any]:
        """Get fallback competitor data from other sources if available"""
        fallback_data = {}
        
        # Try to get competitor data from SWOT analysis results
        swot_analyses = state.get('swot_analyses', {})
        if swot_analyses:
            fallback_data['swot_competitors'] = list(swot_analyses.keys())
        
        # Try to get competitor data from competitor analysis content
        competitor_analysis_structured = state.get('competitor_analysis_structured', {})
        if competitor_analysis_structured:
            fallback_data['structured_competitors'] = competitor_analysis_structured.get('competitors', [])
        
        return fallback_data
    
    def _generate_header_section(self, state: MarketResearchState, report_id: str) -> str:
        """Generate the report header section"""
        return self.section_templates['header'].format(
            target_market=state.get('target_market', 'Unknown Market').title(),
            analysis_type=state.get('analysis_type', '3C Analysis'),
            market_segment=state.get('market_segment', 'General Market'),
            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            report_id=report_id
        )
    
    async def _generate_executive_summary(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the executive summary section"""
        metrics = synthesized_data['key_metrics']
        quality = synthesized_data['data_quality']
        target_market = state.get('target_market', 'target market')
        
        summary_content = f"""This comprehensive 3C analysis of the {target_market} market provides strategic insights across Customer, Company, and Competitor dimensions. The analysis leverages AI-powered research agents to collect and synthesize market intelligence from multiple data sources.

**Analysis Scope:** {target_market.title()} market research focusing on consumer behavior, market trends, competitive landscape, and strategic opportunities.

**Data Quality Score:** {quality['overall_score']:.1%} completeness with {self._format_data_quality(quality['consumer_data_quality'])} consumer insights and {self._format_data_quality(quality['trend_data_quality'])} market intelligence."""
        
        key_findings = f"""- **{metrics['consumer_insights_count']}** consumer insights identified from social media, reviews, and forums
- **{metrics['pain_points_identified']}** consumer pain points documented
- **{metrics['market_trends_identified']}** market trends analyzed from industry sources
- **{metrics['opportunities_identified']}** market opportunities identified
- **{metrics['white_spaces_found']}** white space opportunities discovered
- **{metrics['total_recommendations']}** strategic recommendations generated"""
        
        return self.section_templates['executive_summary'].format(
            summary_content=summary_content,
            key_findings=key_findings
        )
    
    async def _generate_consumer_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the consumer analysis section"""
        consumer_content = []
        
        # Pain points subsection
        pain_points = state.get('pain_points', [])
        if pain_points:
            consumer_content.append("### Key Consumer Pain Points")
            for i, pain_point in enumerate(pain_points[:5], 1):
                consumer_content.append(f"{i}. {pain_point}")
            consumer_content.append("")
        
        # Customer personas subsection
        customer_personas = state.get('customer_personas', [])
        if customer_personas:
            consumer_content.append("### Customer Personas")
            for i, persona in enumerate(customer_personas[:3], 1):
                persona_name = persona.get('name', f'Persona {i}')
                persona_desc = persona.get('description', 'No description available')
                consumer_content.append(f"**{persona_name}:** {persona_desc}")
            consumer_content.append("")
        
        # Consumer insights subsection
        insights = synthesized_data['consumer_insights']
        if insights:
            consumer_content.append("### Consumer Insights")
            for i, insight in enumerate(insights[:5], 1):
                insight_text = insight.get('extracted_insight', '')
                confidence = insight.get('confidence_score', 0)
                source = insight.get('source', 'Unknown')
                consumer_content.append(f"{i}. {insight_text}")
                consumer_content.append(f"   *Source: {source} | Confidence: {confidence:.2f}*")
            consumer_content.append("")
        
        # Purchase journey subsection
        purchase_journey = state.get('purchase_journey', {})
        if purchase_journey:
            consumer_content.append("### Purchase Journey Insights")
            for stage, details in purchase_journey.items():
                if isinstance(details, str):
                    consumer_content.append(f"**{stage.title()}:** {details}")
            consumer_content.append("")
        
        if not consumer_content:
            consumer_content = ["Consumer analysis data is being processed or unavailable.", ""]
        
        return self.section_templates['consumer_analysis'].format(
            consumer_content="\n".join(consumer_content)
        )
    
    async def _generate_trend_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the market trends analysis section"""
        trend_content = []
        
        trends = synthesized_data['market_trends']
        if trends:
            trend_content.append("### Identified Market Trends")
            for i, trend in enumerate(trends[:5], 1):
                trend_text = trend.get('extracted_trends', '')
                confidence = trend.get('confidence_score', 0)
                
                # Enhanced source attribution for real-time data
                source_name = trend.get('source_name', 'Unknown')
                source_category = trend.get('source_category', 'Market Analysis')
                source_url = trend.get('source_url', '')
                reliability_score = trend.get('reliability_score', 0)
                collection_method = trend.get('collection_method', 'search_api')
                data_recency = trend.get('data_recency', '2024_current')
                
                # Format source with proper attribution - only show if we have valid sources
                source_line = ""
                if source_name and source_name != 'Unknown' and source_name.strip():
                    if source_url:
                        source_attribution = f"[{source_name}]({source_url})"
                    else:
                        source_attribution = source_name
                    
                    # Add reliability and recency indicators
                    if reliability_score >= 0.9:
                        reliability_indicator = "High Reliability"
                    elif reliability_score >= 0.7:
                        reliability_indicator = "Medium-High Reliability"
                    else:
                        reliability_indicator = "Medium Reliability"
                    
                    # Add data recency indicator
                    if data_recency == '2024_current':
                        recency_indicator = "Current 2024 Data"
                    else:
                        recency_indicator = "Historical Data"
                        
                    source_line = f"   *Source: {source_attribution} | {source_category} | {reliability_indicator} | {recency_indicator} | Confidence: {confidence:.2f}*"
                elif confidence > 0:
                    # Show only confidence if no valid source
                    source_line = f"   *Confidence: {confidence:.2f}*"
                
                trend_content.append(f"{i}. {trend_text}")
                if source_line.strip():  # Only add source line if it has content
                    trend_content.append(source_line)
            trend_content.append("")
        
        # Trend predictions subsection
        trend_predictions = state.get('trend_predictions', [])
        if trend_predictions:
            trend_content.append("### Trend Predictions")
            for i, prediction in enumerate(trend_predictions[:3], 1):
                title = prediction.get('title', f'Prediction {i}')
                description = prediction.get('description', 'No description available')
                
                # Get source information for predictions
                source_name = prediction.get('source_name', '')
                confidence = prediction.get('confidence_score', 0)
                
                # Format prediction with proper attribution
                if source_name and source_name != 'Unknown':
                    if confidence > 0:
                        trend_content.append(f"**{title}** ({source_name}): {description}")
                        trend_content.append(f"   *Confidence: {confidence:.2f}*")
                    else:
                        trend_content.append(f"**{title}** ({source_name}): {description}")
                else:
                    # If no valid source, show prediction without source attribution
                    trend_content.append(f"**{title}**: {description}")
                    if confidence > 0:
                        trend_content.append(f"   *Confidence: {confidence:.2f}*")
            trend_content.append("")
        
        # Adoption curves subsection
        adoption_curves = state.get('adoption_curves', {})
        if adoption_curves:
            trend_content.append("### Adoption Curve Analysis")
            for trend_name, stage in adoption_curves.items():
                trend_content.append(f"**{trend_name}:** Currently in {stage} stage")
            trend_content.append("")
        
        if not trend_content:
            trend_content = ["Market trend analysis data is being processed or unavailable.", ""]
        
        return self.section_templates['trend_analysis'].format(
            trend_content="\n".join(trend_content)
        )
    
    async def _generate_competitor_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the competitive landscape section"""
        competitor_content = []
        
        competitor_data = synthesized_data['competitor_profiles']
        
        # Handle failed, pending, or unavailable competitor analysis
        if competitor_data.get('status') == 'pending':
            competitor_content.append("### Competitive Analysis Status")
            competitor_content.append("Competitive landscape analysis is pending completion of the competitor analysis agent (Task 4).")
            competitor_content.append("")
            competitor_content.append("**Planned Analysis Includes:**")
            competitor_content.append("- Competitor landscape mapping")
            competitor_content.append("- Competitive positioning analysis")
            competitor_content.append("- Feature comparison matrices")
            competitor_content.append("- White space opportunity identification")
            competitor_content.append("")
        elif competitor_data.get('status') == 'failed':
            competitor_content.append("### Competitive Analysis Status")
            error_message = competitor_data.get('error_message', 'Competitor analysis data unavailable')
            competitor_content.append(f"Competitive landscape analysis encountered an issue: {error_message}")
            competitor_content.append("")
            competitor_content.append("**Note:** Market gap analysis and other insights may still be available below.")
            competitor_content.append("")
        elif competitor_data.get('status') == 'success':
            # Generate competitor landscape subsection
            competitors = competitor_data.get('competitors', [])
            key_players = competitor_data.get('key_players', [])
            
            if competitors:
                competitor_content.append("### Competitor Landscape")
                competitor_content.append(f"**Total Competitors Identified:** {competitor_data.get('total_competitors_found', len(competitors))}")
                competitor_content.append("")
                
                # List key competitors
                competitor_content.append("**Key Competitors:**")
                for i, competitor in enumerate(competitors[:8], 1):
                    competitor_content.append(f"{i}. {competitor}")
                competitor_content.append("")
                
                # List market leaders if available
                if key_players:
                    competitor_content.append("**Market Leaders:**")
                    for i, player in enumerate(key_players[:5], 1):
                        competitor_content.append(f"{i}. {player}")
                    competitor_content.append("")
            
            # Market share data subsection
            market_share_data = competitor_data.get('market_share_data', {})
            if market_share_data:
                competitor_content.append("### Market Share Analysis")
                for company, share in list(market_share_data.items())[:5]:
                    competitor_content.append(f"**{company}:** {share}")
                competitor_content.append("")
            
            # Competitive positioning subsection
            positioning_strategies = competitor_data.get('positioning_strategies', {})
            if positioning_strategies:
                competitor_content.append("### Competitive Positioning Analysis")
                for competitor, strategy in list(positioning_strategies.items())[:5]:
                    competitor_content.append(f"#### {competitor}")
                    
                    market_position = strategy.get('market_position', 'Unknown')
                    competitor_content.append(f"**Market Position:** {market_position.title()}")
                    
                    differentiators = strategy.get('key_differentiators', [])
                    if differentiators:
                        competitor_content.append(f"**Key Differentiators:** {', '.join(differentiators)}")
                    
                    target_segments = strategy.get('target_segments', [])
                    if target_segments:
                        competitor_content.append(f"**Target Segments:** {', '.join(target_segments)}")
                    
                    competitor_content.append("")
            
            # Feature comparison subsection
            feature_comparisons = competitor_data.get('feature_comparisons', [])
            if feature_comparisons:
                competitor_content.append("### Feature Comparison Analysis")
                for comparison in feature_comparisons[:3]:
                    competitor_name = comparison.get('competitor', 'Unknown Competitor')
                    overall_rating = comparison.get('overall_rating', 'medium')
                    
                    competitor_content.append(f"#### {competitor_name}")
                    competitor_content.append(f"**Overall Rating:** {overall_rating.title()}")
                    
                    strengths = comparison.get('strengths', [])
                    if strengths:
                        competitor_content.append(f"**Strengths:** {', '.join(strengths)}")
                    
                    weaknesses = comparison.get('weaknesses', [])
                    if weaknesses:
                        competitor_content.append(f"**Weaknesses:** {', '.join(weaknesses)}")
                    
                    competitor_content.append("")
        
        # Market gaps subsection (always include if available)
        market_gaps = state.get('market_gaps', [])
        if market_gaps:
            competitor_content.append("### Identified Market Gaps")
            for i, gap in enumerate(market_gaps[:5], 1):
                competitor_content.append(f"{i}. {gap}")
            competitor_content.append("")
        
        # Competitive positioning from state (fallback)
        competitive_positioning = state.get('competitive_positioning', {})
        if competitive_positioning and competitive_positioning.get('status') not in ['failed', 'no_data_available'] and not competitor_data.get('positioning_strategies'):
            competitor_content.append("### Additional Competitive Insights")
            competitor_content.append("Additional competitive positioning analysis completed.")
            
            # Include positioning map data if available
            positioning_map = competitive_positioning.get('market_positioning_map', {})
            if positioning_map.get('market_segments'):
                segments = positioning_map['market_segments']
                competitor_content.append(f"**Market Segments Identified:** {', '.join(segments)}")
            
            competitor_content.append("")
        
        # Data quality and source attribution
        if competitor_data.get('status') == 'success':
            data_sources = competitor_data.get('data_sources', 0)
            if data_sources > 0:
                competitor_content.append(f"*Analysis based on {data_sources} data sources*")
                competitor_content.append("")
        
        # Fallback content if no data available
        if not competitor_content:
            competitor_content = ["Competitive landscape analysis data is currently unavailable.", ""]
        
        return self.section_templates['competitor_analysis'].format(
            competitor_content="\n".join(competitor_content)
        )
    
    async def _generate_opportunity_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the market opportunities section"""
        opportunity_content = []
        
        opportunities = synthesized_data['opportunities']
        if opportunities:
            opportunity_content.append("### Strategic Opportunities")
            for i, opp in enumerate(opportunities[:5], 1):
                title = opp.get('title', f'Opportunity {i}')
                description = opp.get('description', 'No description available')
                priority = opp.get('priority', 'Medium')
                
                opportunity_content.append(f"#### {i}. {title}")
                opportunity_content.append(f"**Priority:** {priority}")
                opportunity_content.append(f"{description}")
                
                if opp.get('recommendations'):
                    opportunity_content.append("**Recommendations:**")
                    for rec in opp['recommendations'][:3]:
                        opportunity_content.append(f"- {rec}")
                opportunity_content.append("")
        
        # Strategic recommendations subsection
        recommendations = state.get('recommendations', [])
        if recommendations:
            opportunity_content.append("### Strategic Recommendations")
            for i, rec in enumerate(recommendations[:8], 1):
                opportunity_content.append(f"{i}. {rec}")
            opportunity_content.append("")
        
        if not opportunity_content:
            opportunity_content = ["Market opportunity analysis is being processed or unavailable.", ""]
        
        return self.section_templates['opportunity_analysis'].format(
            opportunity_content="\n".join(opportunity_content)
        )
    
    def _generate_footer_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the report footer section"""
        # Collect data sources with enhanced attribution
        data_sources = set()
        
        consumer_insights = state.get('consumer_insights', {})
        if consumer_insights and consumer_insights.get('structured_insights'):
            for insight in consumer_insights['structured_insights']:
                source = insight.get('source', '')
                if source and source != 'Unknown' and source.strip():
                    data_sources.add(source)
        
        market_trends = state.get('market_trends', {})
        if market_trends and market_trends.get('structured_trends'):
            for trend in market_trends['structured_trends']:
                # Use enhanced source name if available
                source_name = trend.get('source_name', trend.get('source', ''))
                if source_name and source_name != 'Unknown' and source_name.strip():
                    data_sources.add(source_name)
        
        # Only add fallback if we have no valid sources
        if not data_sources:
            data_sources.add('Market Research Database')
        
        data_sources_list = ', '.join(sorted(data_sources)) if data_sources else 'Various online sources'
        confidence_score = f"{synthesized_data['data_quality']['overall_score']:.1%}"
        
        return self.section_templates['footer'].format(
            data_sources=data_sources_list,
            confidence_score=confidence_score
        )
    
    def _generate_error_report(self, state: MarketResearchState, error_message: str) -> str:
        """Generate an error report when report generation fails"""
        target_market = state.get('target_market', 'Unknown Market')
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        return f"""# 3C Analysis Report: {target_market} Market

**Generated:** {timestamp}  
**Status:** Error

## Error Report

An error occurred while generating the comprehensive 3C analysis report:

**Error Details:** {error_message}

## Available Data Summary

The following data was available at the time of the error:

- **Consumer Insights:** {'Available' if state.get('consumer_insights') else 'Not Available'}
- **Market Trends:** {'Available' if state.get('market_trends') else 'Not Available'}
- **Pain Points:** {len(state.get('pain_points', []))} identified
- **Opportunities:** {len(state.get('opportunities', []))} identified

---

*Please check the system logs for detailed error information.*
"""

    def export_to_format(self, report_content: str, format_type: str = 'markdown', 
                        state: Optional[MarketResearchState] = None, 
                        report_metadata: Optional[Dict[str, Any]] = None) -> bytes:
        """
        Export report to different formats with proper formatting and metadata.
        
        Args:
            report_content: The generated markdown report
            format_type: Target format ('markdown', 'html', 'pdf', 'json', 'csv')
            state: MarketResearchState for structured data export
            report_metadata: Additional metadata for the report
            
        Returns:
            bytes: Formatted report content as bytes
        """
        try:
            if format_type == 'markdown':
                return self._export_markdown(report_content, report_metadata)
            elif format_type == 'html':
                return self._export_html(report_content, report_metadata)
            elif format_type == 'pdf':
                return self._export_pdf(report_content, report_metadata)
            elif format_type == 'json':
                if state is None:
                    raise ValueError("State is required for JSON export")
                return self._export_json(state, report_metadata)
            elif format_type == 'csv':
                if state is None:
                    raise ValueError("State is required for CSV export")
                return self._export_csv(state, report_metadata)
            else:
                raise ValueError(f"Unsupported format: {format_type}")
        except Exception as e:
            logger.error(f"Error exporting to {format_type}: {e}")
            raise
    
    def _export_markdown(self, report_content: str, metadata: Optional[Dict[str, Any]] = None) -> bytes:
        """Export report as enhanced Markdown with metadata"""
        enhanced_content = []
        
        # Add metadata header if provided
        if metadata:
            enhanced_content.append("---")
            enhanced_content.append("# Report Metadata")
            for key, value in metadata.items():
                enhanced_content.append(f"{key}: {value}")
            enhanced_content.append("---")
            enhanced_content.append("")
        
        enhanced_content.append(report_content)
        
        # Add export timestamp
        enhanced_content.append("")
        enhanced_content.append("---")
        enhanced_content.append(f"*Exported on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
        
        return "\n".join(enhanced_content).encode('utf-8')
    
    def _export_html(self, report_content: str, metadata: Optional[Dict[str, Any]] = None) -> bytes:
        """Export report as properly formatted HTML"""
        try:
            if not MARKDOWN_AVAILABLE or not JINJA2_AVAILABLE:
                return self._export_html_fallback(report_content, metadata)
            
            # Convert markdown to HTML
            md = markdown.Markdown(extensions=['tables', 'fenced_code', 'toc'])
            html_content = md.convert(report_content)
            
            # Extract title from content
            title_match = re.search(r'^# (.+)', report_content, re.MULTILINE)
            title = title_match.group(1) if title_match else "3C Analysis Report"
            
            # Create template context
            template_context = {
                'title': title,
                'content': html_content,
                'metadata': metadata or {},
                'export_timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            }
            
            # Render HTML template
            template = Template(self.html_template)
            final_html = template.render(**template_context)
            
            return final_html.encode('utf-8')
            
        except Exception as e:
            logger.error(f"Error converting to HTML: {e}")
            return self._export_html_fallback(report_content, metadata)
    
    def _export_html_fallback(self, report_content: str, metadata: Optional[Dict[str, Any]] = None) -> bytes:
        """Fallback HTML export when dependencies are not available"""
        # Extract title from content
        title_match = re.search(r'^# (.+)', report_content, re.MULTILINE)
        title = title_match.group(1) if title_match else "3C Analysis Report"
        
        # Create simple HTML with basic formatting
        html_lines = []
        lines = report_content.split('\n')
        
        for line in lines:
            line = line.strip()
            if line.startswith('# '):
                html_lines.append(f'<h1>{line[2:]}</h1>')
            elif line.startswith('## '):
                html_lines.append(f'<h2>{line[3:]}</h2>')
            elif line.startswith('### '):
                html_lines.append(f'<h3>{line[4:]}</h3>')
            elif line.startswith('- ') or line.startswith('* '):
                html_lines.append(f'<li>{line[2:]}</li>')
            elif line.startswith('**') and line.endswith('**'):
                html_lines.append(f'<strong>{line[2:-2]}</strong>')
            elif line.startswith('*') and line.endswith('*'):
                html_lines.append(f'<em>{line[1:-1]}</em>')
            elif line == '---':
                html_lines.append('<hr>')
            elif line:
                html_lines.append(f'<p>{line}</p>')
            else:
                html_lines.append('<br>')
        
        simple_html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8f9fa;
        }}
        .container {{
            background-color: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; border-left: 4px solid #3498db; padding-left: 15px; }}
        h3 {{ color: #2c3e50; }}
        li {{ margin: 5px 0; }}
        hr {{ border: 1px solid #dee2e6; margin: 20px 0; }}
        .footer {{ margin-top: 50px; padding-top: 20px; border-top: 1px solid #dee2e6; }}
    </style>
</head>
<body>
    <div class="container">
        {''.join(html_lines)}
        <div class="footer">
            <p><em>Exported on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>
        </div>
    </div>
</body>
</html>
        """
        return simple_html.encode('utf-8')
    
    def _export_pdf(self, report_content: str, metadata: Optional[Dict[str, Any]] = None) -> bytes:
        """Export report as PDF using ReportLab"""
        if not REPORTLAB_AVAILABLE:
            logger.warning("ReportLab not available, returning text-based PDF placeholder")
            return self._export_pdf_fallback(report_content, metadata)
        
        try:
            # Create PDF buffer
            buffer = io.BytesIO()
            
            # Create PDF document
            doc = SimpleDocTemplate(
                buffer,
                pagesize=A4,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18
            )
            
            # Get styles
            styles = getSampleStyleSheet()
            
            # Create custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                spaceAfter=30,
                alignment=TA_CENTER,
                textColor=colors.HexColor('#2c3e50')
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=16,
                spaceAfter=12,
                spaceBefore=20,
                textColor=colors.HexColor('#34495e')
            )
            
            body_style = ParagraphStyle(
                'CustomBody',
                parent=styles['Normal'],
                fontSize=11,
                spaceAfter=12,
                alignment=TA_JUSTIFY
            )
            
            # Build PDF content
            story = []
            
            # Add metadata if provided
            if metadata:
                story.append(Paragraph("Report Metadata", heading_style))
                for key, value in metadata.items():
                    story.append(Paragraph(f"<b>{key}:</b> {value}", body_style))
                story.append(Spacer(1, 20))
            
            # Process markdown content
            lines = report_content.split('\n')
            current_paragraph = []
            
            for line in lines:
                line = line.strip()
                
                if not line:
                    if current_paragraph:
                        story.append(Paragraph(' '.join(current_paragraph), body_style))
                        current_paragraph = []
                    continue
                
                # Handle headers
                if line.startswith('# '):
                    if current_paragraph:
                        story.append(Paragraph(' '.join(current_paragraph), body_style))
                        current_paragraph = []
                    story.append(Paragraph(line[2:], title_style))
                elif line.startswith('## '):
                    if current_paragraph:
                        story.append(Paragraph(' '.join(current_paragraph), body_style))
                        current_paragraph = []
                    story.append(Paragraph(line[3:], heading_style))
                elif line.startswith('### '):
                    if current_paragraph:
                        story.append(Paragraph(' '.join(current_paragraph), body_style))
                        current_paragraph = []
                    story.append(Paragraph(f"<b>{line[4:]}</b>", body_style))
                elif line.startswith('---'):
                    if current_paragraph:
                        story.append(Paragraph(' '.join(current_paragraph), body_style))
                        current_paragraph = []
                    story.append(Spacer(1, 12))
                else:
                    # Handle bullet points
                    if line.startswith('- ') or line.startswith('* '):
                        if current_paragraph:
                            story.append(Paragraph(' '.join(current_paragraph), body_style))
                            current_paragraph = []
                        story.append(Paragraph(f"• {line[2:]}", body_style))
                    elif line.startswith(('1. ', '2. ', '3. ', '4. ', '5. ')):
                        if current_paragraph:
                            story.append(Paragraph(' '.join(current_paragraph), body_style))
                            current_paragraph = []
                        story.append(Paragraph(line, body_style))
                    else:
                        current_paragraph.append(line)
            
            # Add any remaining paragraph
            if current_paragraph:
                story.append(Paragraph(' '.join(current_paragraph), body_style))
            
            # Add footer
            story.append(Spacer(1, 30))
            story.append(Paragraph(
                f"Generated by AI-powered 3C Analysis System on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                styles['Normal']
            ))
            
            # Build PDF
            doc.build(story)
            
            # Get PDF bytes
            pdf_bytes = buffer.getvalue()
            buffer.close()
            
            return pdf_bytes
            
        except Exception as e:
            logger.error(f"Error generating PDF: {e}")
            # Return error message as simple PDF
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            styles = getSampleStyleSheet()
            story = [
                Paragraph("PDF Export Error", styles['Title']),
                Paragraph(f"An error occurred while generating the PDF: {str(e)}", styles['Normal']),
                Paragraph("Please try exporting in a different format.", styles['Normal'])
            ]
            doc.build(story)
            pdf_bytes = buffer.getvalue()
            buffer.close()
            return pdf_bytes
    
    def _export_pdf_fallback(self, report_content: str, metadata: Optional[Dict[str, Any]] = None) -> bytes:
        """Fallback PDF export when ReportLab is not available"""
        # Create a simple text-based PDF placeholder
        pdf_placeholder = f"""PDF Export Not Available

ReportLab library is not installed. Please install it to enable PDF export.

Report Content:
{'-' * 50}
{report_content}
{'-' * 50}

Exported on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        return pdf_placeholder.encode('utf-8')
    
    def _export_json(self, state: MarketResearchState, metadata: Optional[Dict[str, Any]] = None) -> bytes:
        """Export structured analysis results as JSON"""
        try:
            # Create structured JSON export
            json_data = {
                'metadata': {
                    'report_id': self._generate_report_id(state),
                    'export_timestamp': datetime.now().isoformat(),
                    'export_format': 'json',
                    'version': self.report_metadata.get('version', '1.0'),
                    'generator': self.report_metadata.get('generator', 'AI-powered 3C Analysis System'),
                    **(metadata or {})
                },
                'analysis_parameters': {
                    'target_market': state.get('target_market', 'Unknown'),
                    'market_segment': state.get('market_segment', 'General'),
                    'analysis_type': state.get('analysis_type', '3C Analysis')
                },
                'consumer_analysis': {
                    'insights': state.get('consumer_insights', {}),
                    'pain_points': state.get('pain_points', []),
                    'customer_personas': state.get('customer_personas', []),
                    'purchase_journey': state.get('purchase_journey', {})
                },
                'trend_analysis': {
                    'market_trends': state.get('market_trends', {}),
                    'trend_predictions': state.get('trend_predictions', []),
                    'adoption_curves': state.get('adoption_curves', {})
                },
                'competitor_analysis': {
                    'competitor_landscape': state.get('competitor_landscape', {}),
                    'competitive_positioning': state.get('competitive_positioning', {}),
                    'feature_comparisons': state.get('feature_comparisons', []),
                    'market_gaps': state.get('market_gaps', [])
                },
                'opportunity_analysis': {
                    'opportunities': state.get('opportunities', []),
                    'white_spaces': state.get('white_spaces', []),
                    'recommendations': state.get('recommendations', [])
                },
                'data_quality': {
                    'sources_count': len(state.get('data_sources', [])),
                    'confidence_scores': self._extract_confidence_scores(state),
                    'completeness_assessment': self._assess_data_quality(state)
                }
            }
            
            return json.dumps(json_data, indent=2, ensure_ascii=False, default=str).encode('utf-8')
            
        except Exception as e:
            logger.error(f"Error generating JSON export: {e}")
            error_json = {
                'error': 'JSON export failed',
                'message': str(e),
                'timestamp': datetime.now().isoformat()
            }
            return json.dumps(error_json, indent=2).encode('utf-8')
    
    def _export_csv(self, state: MarketResearchState, metadata: Optional[Dict[str, Any]] = None) -> bytes:
        """Export competitor comparison and key metrics as CSV"""
        try:
            output = io.StringIO()
            
            # Write metadata header
            if metadata:
                output.write("# Report Metadata\n")
                for key, value in metadata.items():
                    output.write(f"# {key}: {value}\n")
                output.write("\n")
            
            # Export competitor comparison matrix
            competitor_landscape = state.get('competitor_landscape', {})
            feature_comparisons = state.get('feature_comparisons', [])
            
            if competitor_landscape.get('competitors') or feature_comparisons:
                output.write("# Competitor Analysis\n")
                
                # Competitor overview
                competitors = competitor_landscape.get('competitors', [])
                key_players = competitor_landscape.get('key_players', [])
                
                if competitors:
                    writer = csv.writer(output)
                    writer.writerow(['Competitor Type', 'Company Name', 'Market Position'])
                    
                    for competitor in competitors[:10]:  # Limit to top 10
                        competitor_name = competitor if isinstance(competitor, str) else str(competitor)
                        position = 'Key Player' if competitor_name in key_players else 'Competitor'
                        writer.writerow(['Competitor', competitor_name, position])
                    
                    output.write("\n")
                
                # Feature comparison matrix
                if feature_comparisons:
                    output.write("# Feature Comparison Matrix\n")
                    writer = csv.writer(output)
                    
                    # Extract all unique features
                    all_features = set()
                    for comparison in feature_comparisons:
                        if isinstance(comparison, dict) and 'features' in comparison:
                            all_features.update(comparison['features'].keys())
                    
                    if all_features:
                        # Create header
                        header = ['Competitor'] + list(all_features)
                        writer.writerow(header)
                        
                        # Write feature data
                        for comparison in feature_comparisons[:10]:  # Limit to top 10
                            if isinstance(comparison, dict):
                                row = [comparison.get('competitor', 'Unknown')]
                                features = comparison.get('features', {})
                                for feature in all_features:
                                    row.append(features.get(feature, 'N/A'))
                                writer.writerow(row)
                    
                    output.write("\n")
            
            # Export key metrics summary
            output.write("# Key Metrics Summary\n")
            writer = csv.writer(output)
            writer.writerow(['Metric', 'Value', 'Category'])
            
            # Consumer metrics
            consumer_insights = state.get('consumer_insights', {})
            if consumer_insights.get('structured_insights'):
                writer.writerow(['Consumer Insights Count', len(consumer_insights['structured_insights']), 'Consumer Analysis'])
            
            pain_points = state.get('pain_points', [])
            writer.writerow(['Pain Points Identified', len(pain_points), 'Consumer Analysis'])
            
            # Trend metrics
            market_trends = state.get('market_trends', {})
            if market_trends.get('structured_trends'):
                writer.writerow(['Market Trends Identified', len(market_trends['structured_trends']), 'Trend Analysis'])
            
            trend_predictions = state.get('trend_predictions', [])
            writer.writerow(['Trend Predictions', len(trend_predictions), 'Trend Analysis'])
            
            # Competitor metrics
            if competitors:
                writer.writerow(['Competitors Identified', len(competitors), 'Competitor Analysis'])
            
            # Opportunity metrics
            opportunities = state.get('opportunities', [])
            writer.writerow(['Opportunities Identified', len(opportunities), 'Opportunity Analysis'])
            
            white_spaces = state.get('white_spaces', [])
            writer.writerow(['White Spaces Found', len(white_spaces), 'Opportunity Analysis'])
            
            output.write("\n")
            
            # Export opportunities detail
            if opportunities:
                output.write("# Market Opportunities Detail\n")
                writer = csv.writer(output)
                writer.writerow(['Opportunity Title', 'Description', 'Priority', 'Market Size', 'Competition Level'])
                
                for opp in opportunities[:10]:  # Limit to top 10
                    if isinstance(opp, dict):
                        writer.writerow([
                            opp.get('title', 'N/A'),
                            opp.get('description', 'N/A')[:100] + '...' if len(opp.get('description', '')) > 100 else opp.get('description', 'N/A'),
                            opp.get('priority', 'N/A'),
                            opp.get('market_size', 'N/A'),
                            opp.get('competition_level', 'N/A')
                        ])
            
            # Add export timestamp
            output.write(f"\n# Exported on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            
            return output.getvalue().encode('utf-8')
            
        except Exception as e:
            logger.error(f"Error generating CSV export: {e}")
            error_csv = f"Error,Message,Timestamp\nCSV Export Failed,{str(e)},{datetime.now().isoformat()}\n"
            return error_csv.encode('utf-8')
    
    def _extract_confidence_scores(self, state: MarketResearchState) -> Dict[str, float]:
        """Extract confidence scores from analysis results"""
        confidence_scores = {}
        
        # Consumer analysis confidence
        consumer_insights = state.get('consumer_insights', {})
        if consumer_insights.get('structured_insights'):
            scores = [insight.get('confidence_score', 0) for insight in consumer_insights['structured_insights']]
            confidence_scores['consumer_analysis'] = sum(scores) / len(scores) if scores else 0.0
        
        # Trend analysis confidence
        market_trends = state.get('market_trends', {})
        if market_trends.get('structured_trends'):
            scores = [trend.get('confidence_score', 0) for trend in market_trends['structured_trends']]
            confidence_scores['trend_analysis'] = sum(scores) / len(scores) if scores else 0.0
        
        # Overall confidence
        if confidence_scores:
            confidence_scores['overall'] = sum(confidence_scores.values()) / len(confidence_scores)
        
        return confidence_scores
    
    def generate_export_metadata(self, state: MarketResearchState, format_type: str) -> Dict[str, Any]:
        """Generate metadata for report exports"""
        return {
            'report_id': self._generate_report_id(state),
            'target_market': state.get('target_market', 'Unknown'),
            'analysis_type': state.get('analysis_type', '3C Analysis'),
            'export_format': format_type,
            'export_timestamp': datetime.now().isoformat(),
            'version': self.report_metadata.get('version', '1.0'),
            'generator': self.report_metadata.get('generator', 'AI-powered 3C Analysis System'),
            'data_sources_count': len(state.get('data_sources', [])),
            'analysis_completeness': self._assess_data_quality(state).get('data_completeness', 0.0)
        }
    
    def generate_export_filename(self, state: MarketResearchState, format_type: str) -> str:
        """Generate appropriate filename for export format"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        market = state.get('target_market', 'unknown').replace(' ', '_').lower()
        market = re.sub(r'[^\w\-_]', '', market)  # Remove special characters
        
        base_filename = f"3c_analysis_{market}_{timestamp}"
        
        extensions = {
            'markdown': '.md',
            'html': '.html',
            'pdf': '.pdf',
            'json': '.json',
            'csv': '.csv'
        }
        
        return base_filename + extensions.get(format_type, '.txt')