"""
Market Research Report Generation System

This module provides comprehensive report generation capabilities for 3C analysis,
extending the existing reporting infrastructure with specialized market research formatting.
"""

import logging
from typing import Dict, List, Any, Optional, Set
from datetime import datetime
from dataclasses import asdict
import re

from backend.classes.state import MarketResearchState, ConsumerInsight, MarketTrend, CompetitorProfile, MarketOpportunity

logger = logging.getLogger(__name__)


class MarketResearchReportGenerator:
    """
    Generates comprehensive 3C analysis reports with structured formatting,
    insight synthesis, and duplicate removal capabilities.
    """
    
    def __init__(self):
        self.export_formats = ['markdown', 'html', 'pdf']
        self.section_templates = self._initialize_templates()
        
    def _initialize_templates(self) -> Dict[str, str]:
        """Initialize report section templates"""
        return {
            'header': """# 3C Analysis Report: {target_market} Market

**Analysis Type:** {analysis_type}  
**Market Segment:** {market_segment}  
**Generated:** {timestamp}  
**Report ID:** {report_id}

---
""",
            'executive_summary': """## Executive Summary

{summary_content}

### Key Findings
{key_findings}

---
""",
            'consumer_analysis': """## Consumer Analysis

{consumer_content}

---
""",
            'trend_analysis': """## Market Trends Analysis

{trend_content}

---
""",
            'competitor_analysis': """## Competitive Landscape

{competitor_content}

---
""",
            'opportunity_analysis': """## Market Opportunities

{opportunity_content}

---
""",
            'footer': """---

### Report Metadata
- **Data Sources:** {data_sources}
- **Analysis Confidence:** {confidence_score}
- **Report Version:** 1.0

*This report was generated by the AI-powered 3C Analysis System*
"""
        }
    
    async def generate_3c_report(self, state: MarketResearchState) -> str:
        """
        Generate a comprehensive 3C analysis report from the market research state.
        
        Args:
            state: MarketResearchState containing all analysis results
            
        Returns:
            str: Formatted markdown report
        """
        try:
            logger.info(f"Generating 3C report for {state.get('target_market', 'Unknown Market')}")
            
            # Generate unique report ID
            report_id = self._generate_report_id(state)
            
            # Synthesize insights and remove duplicates
            synthesized_data = await self._synthesize_insights(state)
            
            # Build report sections
            sections = []
            
            # Header section
            sections.append(self._generate_header_section(state, report_id))
            
            # Executive summary
            sections.append(await self._generate_executive_summary(state, synthesized_data))
            
            # Consumer analysis section
            sections.append(await self._generate_consumer_section(state, synthesized_data))
            
            # Trend analysis section
            sections.append(await self._generate_trend_section(state, synthesized_data))
            
            # Competitor analysis section
            sections.append(await self._generate_competitor_section(state, synthesized_data))
            
            # Opportunity analysis section
            sections.append(await self._generate_opportunity_section(state, synthesized_data))
            
            # Footer section
            sections.append(self._generate_footer_section(state, synthesized_data))
            
            # Combine all sections
            full_report = "\n".join(sections)
            
            logger.info(f"Successfully generated 3C report ({len(full_report)} characters)")
            return full_report
            
        except Exception as e:
            logger.error(f"Error generating 3C report: {e}")
            return self._generate_error_report(state, str(e))
    
    def _generate_report_id(self, state: MarketResearchState) -> str:
        """Generate a unique report identifier"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        market = state.get('target_market', 'unknown').replace(' ', '_').lower()
        return f"3c_{market}_{timestamp}"
    
    async def _synthesize_insights(self, state: MarketResearchState) -> Dict[str, Any]:
        """
        Synthesize and deduplicate insights from all analysis agents.
        
        Returns:
            Dict containing synthesized and deduplicated data
        """
        synthesized = {
            'consumer_insights': self._deduplicate_consumer_insights(state),
            'market_trends': self._deduplicate_market_trends(state),
            'competitor_profiles': self._deduplicate_competitor_data(state),
            'opportunities': self._deduplicate_opportunities(state),
            'data_quality': self._assess_data_quality(state),
            'key_metrics': self._calculate_key_metrics(state)
        }
        
        return synthesized
    
    def _deduplicate_consumer_insights(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Remove duplicate consumer insights based on content similarity"""
        consumer_insights = state.get('consumer_insights', {})
        
        if not consumer_insights or not consumer_insights.get('structured_insights'):
            return []
        
        insights = consumer_insights['structured_insights']
        deduplicated = []
        seen_content = set()
        
        for insight in insights:
            content = insight.get('extracted_insight', '').lower().strip()
            
            # Create a normalized version for comparison
            normalized = re.sub(r'[^\w\s]', '', content)
            normalized = ' '.join(normalized.split())
            
            # Check for similarity with existing insights
            is_duplicate = False
            for seen in seen_content:
                if self._calculate_similarity(normalized, seen) > 0.6:  # Lower threshold for better deduplication
                    is_duplicate = True
                    break
            
            if not is_duplicate and len(normalized) > 10:
                seen_content.add(normalized)
                deduplicated.append(insight)
        
        return deduplicated[:10]  # Limit to top 10 insights
    
    def _deduplicate_market_trends(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Remove duplicate market trends based on content similarity"""
        market_trends = state.get('market_trends', {})
        
        if not market_trends or not market_trends.get('structured_trends'):
            return []
        
        trends = market_trends['structured_trends']
        deduplicated = []
        seen_trends = set()
        
        for trend in trends:
            trend_text = trend.get('extracted_trends', '').lower().strip()
            
            # Normalize trend text
            normalized = re.sub(r'[^\w\s]', '', trend_text)
            normalized = ' '.join(normalized.split())
            
            # Check for duplicates
            is_duplicate = False
            for seen in seen_trends:
                if self._calculate_similarity(normalized, seen) > 0.7:
                    is_duplicate = True
                    break
            
            if not is_duplicate and len(normalized) > 10:
                seen_trends.add(normalized)
                deduplicated.append(trend)
        
        return deduplicated[:8]  # Limit to top 8 trends
    
    def _deduplicate_competitor_data(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Process and deduplicate competitor analysis data"""
        competitor_landscape = state.get('competitor_landscape', {})
        
        if not competitor_landscape or competitor_landscape.get('status') == 'failed':
            return []
        
        # For now, return placeholder structure since competitor agent isn't implemented
        return [{
            'name': 'Competitor Analysis Pending',
            'status': 'Awaiting competitor analysis agent implementation',
            'note': 'Detailed competitor profiles will be available once task 4 is completed'
        }]
    
    def _deduplicate_opportunities(self, state: MarketResearchState) -> List[Dict[str, Any]]:
        """Remove duplicate opportunities and white spaces"""
        opportunities = state.get('opportunities', [])
        white_spaces = state.get('white_spaces', [])
        
        all_opportunities = opportunities + white_spaces
        deduplicated = []
        seen_titles = set()
        
        for opp in all_opportunities:
            title = opp.get('title', '').lower().strip()
            
            if title and title not in seen_titles:
                seen_titles.add(title)
                deduplicated.append(opp)
        
        return deduplicated[:6]  # Limit to top 6 opportunities
    
    def _calculate_similarity(self, text1: str, text2: str) -> float:
        """Calculate simple similarity score between two text strings"""
        if not text1 or not text2:
            return 0.0
        
        words1 = set(text1.split())
        words2 = set(text2.split())
        
        if not words1 or not words2:
            return 0.0
        
        intersection = words1.intersection(words2)
        union = words1.union(words2)
        
        return len(intersection) / len(union) if union else 0.0
    
    def _assess_data_quality(self, state: MarketResearchState) -> Dict[str, Any]:
        """Assess the quality and completeness of collected data"""
        quality_metrics = {
            'overall_score': 0.0,
            'consumer_data_quality': 'unknown',
            'trend_data_quality': 'unknown',
            'competitor_data_quality': 'unknown',
            'data_completeness': 0.0
        }
        
        # Assess consumer data quality
        consumer_insights = state.get('consumer_insights', {})
        if consumer_insights and consumer_insights.get('structured_insights'):
            insights_count = len(consumer_insights['structured_insights'])
            quality_metrics['consumer_data_quality'] = 'high' if insights_count >= 5 else 'medium' if insights_count >= 2 else 'low'
        
        # Assess trend data quality
        market_trends = state.get('market_trends', {})
        if market_trends and market_trends.get('structured_trends'):
            trends_count = len(market_trends['structured_trends'])
            quality_metrics['trend_data_quality'] = 'high' if trends_count >= 3 else 'medium' if trends_count >= 1 else 'low'
        
        # Assess competitor data quality
        competitor_landscape = state.get('competitor_landscape', {})
        if competitor_landscape and competitor_landscape.get('status') != 'failed':
            quality_metrics['competitor_data_quality'] = 'pending'
        else:
            quality_metrics['competitor_data_quality'] = 'unavailable'
        
        # Calculate overall completeness
        completeness_factors = []
        if quality_metrics['consumer_data_quality'] in ['high', 'medium']:
            completeness_factors.append(1.0)
        if quality_metrics['trend_data_quality'] in ['high', 'medium']:
            completeness_factors.append(1.0)
        if quality_metrics['competitor_data_quality'] in ['high', 'medium']:
            completeness_factors.append(1.0)
        
        quality_metrics['data_completeness'] = sum(completeness_factors) / 3.0
        quality_metrics['overall_score'] = quality_metrics['data_completeness']
        
        return quality_metrics
    
    def _calculate_key_metrics(self, state: MarketResearchState) -> Dict[str, int]:
        """Calculate key metrics for the executive summary"""
        consumer_insights = state.get('consumer_insights', {})
        market_trends = state.get('market_trends', {})
        pain_points = state.get('pain_points', [])
        opportunities = state.get('opportunities', [])
        white_spaces = state.get('white_spaces', [])
        
        return {
            'consumer_insights_count': len(consumer_insights.get('structured_insights', [])),
            'pain_points_identified': len(pain_points),
            'market_trends_identified': len(market_trends.get('structured_trends', [])),
            'opportunities_identified': len(opportunities),
            'white_spaces_found': len(white_spaces),
            'total_recommendations': len(state.get('recommendations', []))
        }
    
    def _format_data_quality(self, quality: str) -> str:
        """Format data quality description to avoid 'unknown'"""
        if quality == 'unknown':
            return 'pending'
        elif quality == 'unavailable':
            return 'not available'
        else:
            return quality
    
    def _generate_header_section(self, state: MarketResearchState, report_id: str) -> str:
        """Generate the report header section"""
        return self.section_templates['header'].format(
            target_market=state.get('target_market', 'Unknown Market').title(),
            analysis_type=state.get('analysis_type', '3C Analysis'),
            market_segment=state.get('market_segment', 'General Market'),
            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            report_id=report_id
        )
    
    async def _generate_executive_summary(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the executive summary section"""
        metrics = synthesized_data['key_metrics']
        quality = synthesized_data['data_quality']
        target_market = state.get('target_market', 'target market')
        
        summary_content = f"""This comprehensive 3C analysis of the {target_market} market provides strategic insights across Customer, Company, and Competitor dimensions. The analysis leverages AI-powered research agents to collect and synthesize market intelligence from multiple data sources.

**Analysis Scope:** {target_market.title()} market research focusing on consumer behavior, market trends, competitive landscape, and strategic opportunities.

**Data Quality Score:** {quality['overall_score']:.1%} completeness with {self._format_data_quality(quality['consumer_data_quality'])} consumer insights and {self._format_data_quality(quality['trend_data_quality'])} market intelligence."""
        
        key_findings = f"""- **{metrics['consumer_insights_count']}** consumer insights identified from social media, reviews, and forums
- **{metrics['pain_points_identified']}** consumer pain points documented
- **{metrics['market_trends_identified']}** market trends analyzed from industry sources
- **{metrics['opportunities_identified']}** market opportunities identified
- **{metrics['white_spaces_found']}** white space opportunities discovered
- **{metrics['total_recommendations']}** strategic recommendations generated"""
        
        return self.section_templates['executive_summary'].format(
            summary_content=summary_content,
            key_findings=key_findings
        )
    
    async def _generate_consumer_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the consumer analysis section"""
        consumer_content = []
        
        # Pain points subsection
        pain_points = state.get('pain_points', [])
        if pain_points:
            consumer_content.append("### Key Consumer Pain Points")
            for i, pain_point in enumerate(pain_points[:5], 1):
                consumer_content.append(f"{i}. {pain_point}")
            consumer_content.append("")
        
        # Customer personas subsection
        customer_personas = state.get('customer_personas', [])
        if customer_personas:
            consumer_content.append("### Customer Personas")
            for i, persona in enumerate(customer_personas[:3], 1):
                persona_name = persona.get('name', f'Persona {i}')
                persona_desc = persona.get('description', 'No description available')
                consumer_content.append(f"**{persona_name}:** {persona_desc}")
            consumer_content.append("")
        
        # Consumer insights subsection
        insights = synthesized_data['consumer_insights']
        if insights:
            consumer_content.append("### Consumer Insights")
            for i, insight in enumerate(insights[:5], 1):
                insight_text = insight.get('extracted_insight', '')
                confidence = insight.get('confidence_score', 0)
                source = insight.get('source', 'Unknown')
                consumer_content.append(f"{i}. {insight_text}")
                consumer_content.append(f"   *Source: {source} | Confidence: {confidence:.2f}*")
            consumer_content.append("")
        
        # Purchase journey subsection
        purchase_journey = state.get('purchase_journey', {})
        if purchase_journey:
            consumer_content.append("### Purchase Journey Insights")
            for stage, details in purchase_journey.items():
                if isinstance(details, str):
                    consumer_content.append(f"**{stage.title()}:** {details}")
            consumer_content.append("")
        
        if not consumer_content:
            consumer_content = ["Consumer analysis data is being processed or unavailable.", ""]
        
        return self.section_templates['consumer_analysis'].format(
            consumer_content="\n".join(consumer_content)
        )
    
    async def _generate_trend_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the market trends analysis section"""
        trend_content = []
        
        trends = synthesized_data['market_trends']
        if trends:
            trend_content.append("### Identified Market Trends")
            for i, trend in enumerate(trends[:5], 1):
                trend_text = trend.get('extracted_trends', '')
                confidence = trend.get('confidence_score', 0)
                
                # Enhanced source attribution for real-time data
                source_name = trend.get('source_name', 'Unknown')
                source_category = trend.get('source_category', 'Market Analysis')
                source_url = trend.get('source_url', '')
                reliability_score = trend.get('reliability_score', 0)
                collection_method = trend.get('collection_method', 'search_api')
                data_recency = trend.get('data_recency', '2024_current')
                
                # Format source with proper attribution - only show if we have valid sources
                source_line = ""
                if source_name and source_name != 'Unknown' and source_name.strip():
                    if source_url:
                        source_attribution = f"[{source_name}]({source_url})"
                    else:
                        source_attribution = source_name
                    
                    # Add reliability and recency indicators
                    if reliability_score >= 0.9:
                        reliability_indicator = "High Reliability"
                    elif reliability_score >= 0.7:
                        reliability_indicator = "Medium-High Reliability"
                    else:
                        reliability_indicator = "Medium Reliability"
                    
                    # Add data recency indicator
                    if data_recency == '2024_current':
                        recency_indicator = "Current 2024 Data"
                    else:
                        recency_indicator = "Historical Data"
                        
                    source_line = f"   *Source: {source_attribution} | {source_category} | {reliability_indicator} | {recency_indicator} | Confidence: {confidence:.2f}*"
                elif confidence > 0:
                    # Show only confidence if no valid source
                    source_line = f"   *Confidence: {confidence:.2f}*"
                
                trend_content.append(f"{i}. {trend_text}")
                if source_line.strip():  # Only add source line if it has content
                    trend_content.append(source_line)
            trend_content.append("")
        
        # Trend predictions subsection
        trend_predictions = state.get('trend_predictions', [])
        if trend_predictions:
            trend_content.append("### Trend Predictions")
            for i, prediction in enumerate(trend_predictions[:3], 1):
                title = prediction.get('title', f'Prediction {i}')
                description = prediction.get('description', 'No description available')
                
                # Get source information for predictions
                source_name = prediction.get('source_name', '')
                confidence = prediction.get('confidence_score', 0)
                
                # Format prediction with proper attribution
                if source_name and source_name != 'Unknown':
                    if confidence > 0:
                        trend_content.append(f"**{title}** ({source_name}): {description}")
                        trend_content.append(f"   *Confidence: {confidence:.2f}*")
                    else:
                        trend_content.append(f"**{title}** ({source_name}): {description}")
                else:
                    # If no valid source, show prediction without source attribution
                    trend_content.append(f"**{title}**: {description}")
                    if confidence > 0:
                        trend_content.append(f"   *Confidence: {confidence:.2f}*")
            trend_content.append("")
        
        # Adoption curves subsection
        adoption_curves = state.get('adoption_curves', {})
        if adoption_curves:
            trend_content.append("### Adoption Curve Analysis")
            for trend_name, stage in adoption_curves.items():
                trend_content.append(f"**{trend_name}:** Currently in {stage} stage")
            trend_content.append("")
        
        if not trend_content:
            trend_content = ["Market trend analysis data is being processed or unavailable.", ""]
        
        return self.section_templates['trend_analysis'].format(
            trend_content="\n".join(trend_content)
        )
    
    async def _generate_competitor_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the competitive landscape section"""
        competitor_content = []
        
        competitors = synthesized_data['competitor_profiles']
        if competitors:
            for competitor in competitors:
                if competitor.get('status') == 'Awaiting competitor analysis agent implementation':
                    competitor_content.append("### Competitive Analysis Status")
                    competitor_content.append("Competitive landscape analysis is pending completion of the competitor analysis agent (Task 4).")
                    competitor_content.append("")
                    competitor_content.append("**Planned Analysis Includes:**")
                    competitor_content.append("- Competitor landscape mapping")
                    competitor_content.append("- Competitive positioning analysis")
                    competitor_content.append("- Feature comparison matrices")
                    competitor_content.append("- White space opportunity identification")
                    break
        
        # Market gaps subsection
        market_gaps = state.get('market_gaps', [])
        if market_gaps:
            competitor_content.append("### Identified Market Gaps")
            for i, gap in enumerate(market_gaps[:3], 1):
                competitor_content.append(f"{i}. {gap}")
            competitor_content.append("")
        
        # Competitive positioning subsection
        competitive_positioning = state.get('competitive_positioning', {})
        if competitive_positioning and competitive_positioning.get('status') != 'failed':
            competitor_content.append("### Competitive Positioning")
            competitor_content.append("Competitive positioning analysis available - detailed positioning maps completed.")
            competitor_content.append("")
        
        if not competitor_content:
            competitor_content = ["Competitive landscape analysis is pending implementation.", ""]
        
        return self.section_templates['competitor_analysis'].format(
            competitor_content="\n".join(competitor_content)
        )
    
    async def _generate_opportunity_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the market opportunities section"""
        opportunity_content = []
        
        opportunities = synthesized_data['opportunities']
        if opportunities:
            opportunity_content.append("### Strategic Opportunities")
            for i, opp in enumerate(opportunities[:5], 1):
                title = opp.get('title', f'Opportunity {i}')
                description = opp.get('description', 'No description available')
                priority = opp.get('priority', 'Medium')
                
                opportunity_content.append(f"#### {i}. {title}")
                opportunity_content.append(f"**Priority:** {priority}")
                opportunity_content.append(f"{description}")
                
                if opp.get('recommendations'):
                    opportunity_content.append("**Recommendations:**")
                    for rec in opp['recommendations'][:3]:
                        opportunity_content.append(f"- {rec}")
                opportunity_content.append("")
        
        # Strategic recommendations subsection
        recommendations = state.get('recommendations', [])
        if recommendations:
            opportunity_content.append("### Strategic Recommendations")
            for i, rec in enumerate(recommendations[:8], 1):
                opportunity_content.append(f"{i}. {rec}")
            opportunity_content.append("")
        
        if not opportunity_content:
            opportunity_content = ["Market opportunity analysis is being processed or unavailable.", ""]
        
        return self.section_templates['opportunity_analysis'].format(
            opportunity_content="\n".join(opportunity_content)
        )
    
    def _generate_footer_section(self, state: MarketResearchState, synthesized_data: Dict[str, Any]) -> str:
        """Generate the report footer section"""
        # Collect data sources with enhanced attribution
        data_sources = set()
        
        consumer_insights = state.get('consumer_insights', {})
        if consumer_insights and consumer_insights.get('structured_insights'):
            for insight in consumer_insights['structured_insights']:
                source = insight.get('source', '')
                if source and source != 'Unknown' and source.strip():
                    data_sources.add(source)
        
        market_trends = state.get('market_trends', {})
        if market_trends and market_trends.get('structured_trends'):
            for trend in market_trends['structured_trends']:
                # Use enhanced source name if available
                source_name = trend.get('source_name', trend.get('source', ''))
                if source_name and source_name != 'Unknown' and source_name.strip():
                    data_sources.add(source_name)
        
        # Only add fallback if we have no valid sources
        if not data_sources:
            data_sources.add('Market Research Database')
        
        data_sources_list = ', '.join(sorted(data_sources)) if data_sources else 'Various online sources'
        confidence_score = f"{synthesized_data['data_quality']['overall_score']:.1%}"
        
        return self.section_templates['footer'].format(
            data_sources=data_sources_list,
            confidence_score=confidence_score
        )
    
    def _generate_error_report(self, state: MarketResearchState, error_message: str) -> str:
        """Generate an error report when report generation fails"""
        target_market = state.get('target_market', 'Unknown Market')
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        return f"""# 3C Analysis Report: {target_market} Market

**Generated:** {timestamp}  
**Status:** Error

## Error Report

An error occurred while generating the comprehensive 3C analysis report:

**Error Details:** {error_message}

## Available Data Summary

The following data was available at the time of the error:

- **Consumer Insights:** {'Available' if state.get('consumer_insights') else 'Not Available'}
- **Market Trends:** {'Available' if state.get('market_trends') else 'Not Available'}
- **Pain Points:** {len(state.get('pain_points', []))} identified
- **Opportunities:** {len(state.get('opportunities', []))} identified

---

*Please check the system logs for detailed error information.*
"""

    def export_to_format(self, report_content: str, format_type: str = 'markdown') -> str:
        """
        Export report to different formats (placeholder for future enhancement).
        
        Args:
            report_content: The generated markdown report
            format_type: Target format ('markdown', 'html', 'pdf')
            
        Returns:
            str: Formatted report content
        """
        if format_type == 'markdown':
            return report_content
        elif format_type == 'html':
            # Placeholder for HTML conversion
            return f"<html><body><pre>{report_content}</pre></body></html>"
        elif format_type == 'pdf':
            # Placeholder for PDF conversion
            return report_content
        else:
            raise ValueError(f"Unsupported format: {format_type}")